version: 0.2

phases:
  pre_build:
    commands:
      - echo "Granting execution permissions to docker-install.sh..."
      - chmod +x docker-install.sh
  build:
    commands:
      - echo "Running docker-install.sh script..."
      - ./docker-install.sh
      - echo "Creating installation directory and blank files..."
      - mkdir -p installation
      - touch installation/file1.txt
      - touch installation/file2.txt
      - echo "Saurabh here, put this data in file1.txt using above" > installation/file1.txt
      - cd installation 
      - pwd
  post_build:
    commands:
      - echo "Script execution completed!"

artifacts:
  files:
    - '**/*'
